imports:
    - { resource: @PlanITBundle/Resources/config/security.yml }

security:
    #encoders:
    #    Symfony\Component\Security\Core\User\User: plaintext

    #providers:
    #    in_memory:
    #        users:
    #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    #firewalls:
    #    dev:
    #        pattern:  ^/(_(profiler|wdt)|css|images|js)/
    #        security: false
    #
    #    login:
    #        pattern:  ^/demo/secured/login$
    #        security: false
    #
    #    secured_area:
    #        pattern:    ^/demo/secured/
    #        form_login:
    #            check_path: /demo/secured/login_check
    #            login_path: /demo/secured/login
    #        logout:
    #            path:   /demo/secured/logout
    #            target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    #access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
